#ifndef REVOLUTION_OS_OSMEMMAP_H
#define REVOLUTION_OS_OSMEMMAP_H

#define OS_ADDR_IPC_BUFFER_START 0x3130
#define OS_ADDR_IPC_BUFFER_END 0x3134
#define OS_PHYS_SC_PRDINFO 0x3800

#endif  // REVOLUTION_OS_OSMEMMAP_H
