# Mario Strikers Charged (USA), disc revision 1.
# See config.example.yml for documentation.
object_base: orig/R4QE01
object: sys/main.dol
hash: e96d2298067b70652752145b4e63644e6e1b1560
extract_objects: true
symbols: config/R4QE01/symbols.txt
splits: config/R4QE01/splits.txt
mw_comment_version: 14 # GC Linker 3.0+
add_relocations:
  - { source: .text:0x8009A7CC, type: ha, target: __vt__6Bobomb }
  - { source: .text:0x8009A7D8, type: ha, target: __vt__10GreenShell }
  - { source: .text:0x8009A7F0, type: ha, target: __vt__11FreezeShell }
  - { source: .text:0x8009A7F4, type: l, target: __vt__6Bobomb }
  - { source: .text:0x8009A810, type: ha, target: __vt__8RedShell }
  - { source: .text:0x8009A814, type: l, target: __vt__10GreenShell }
  - { source: .text:0x8009A834, type: l, target: __vt__11FreezeShell }
  - { source: .text:0x8009A854, type: l, target: __vt__8RedShell }
block_relocations:
  # WPADEncrypt.c tb[] bytes that scan as plausible pointers
  - { source: 0x8054BA9C }
  - { source: 0x8054BF10 }
  - { source: 0x8054C090 }
  - { source: 0x804EFFD0 }
  - { source: 0x804EFFD4 }
  - { source: 0x804EFFD8 }
  - { source: 0x8052D1E0 }
  - { source: 0x8052D1E4 }
  - { source: 0x8052D258 }
  - { source: 0x8052D49C }
  - { source: 0x8052DC30 }
  - { source: 0x8052DC34 }
  - { source: 0x8052DC90 }
  - { source: 0x8052DE80 }
force_active:
  - __init_cpp_exceptions_reference
  - __destroy_global_chain_reference
  - __fini_cpp_exceptions_reference
