#ifndef GAME_BASE_GAME_SCENE_MANAGER_H
#define GAME_BASE_GAME_SCENE_MANAGER_H

#include "Game/BaseSceneHandler.h"

enum SceneList
{
    SCENE_INVALID = -2,
    SCENE_TITLE = 0,
    SCENE_MAIN_MENU = 1,
    SCENE_CHOOSE_CAPTAINS_DOMINATION = 2,
    SCENE_CHOOSE_SIDEKICKS_DOMINATION = 3,
    SCENE_CHOOSE_SIDES_DOMINATION = 4,
    SCENE_CHOOSE_STADIUM = 5,
    SCENE_CHOOSE_CAPTAINS_STRIKER_CUP = 6,
    SCENE_CHOOSE_SIDEKICKS_STRIKER_CUP = 7,
    SCENE_CHOOSE_SIDES_STRIKER_CUP = 8,
    SCENE_CUP_CHEATER = 9,
    SCENE_POPUP_MENU = 10,
    SCENE_SPOILS_MENU = 11,
    SCENE_CUSTOM_TOURNAMENT_OPTIONS = 12,
    SCENE_OPTIONS = 13,
    SCENE_AUDIO_OPTIONS = 14,
    SCENE_VISUAL_OPTIONS = 15,
    SCENE_LEGAL = 16,
    SCENE_SUPER_LOADING = 17,
    SCENE_BOOT_LOADING = 18,
    SCENE_BOOT_LOADING_JPN = 19,
    SCENE_MOVIE_PLAYER = 20,
    SCENE_NLG_LOGO = 21,
    SCENE_INTRO_MOVIE = 22,
    SCENE_CREDITS = 23,
    SCENE_NETWORK_START = 24,
    SCENE_ASYNC_LOADING = 25,
    SCENE_WIDESCREEN_LOADING = 26,
    SCENE_GAMEPLAY_OPTIONS = 27,
    SCENE_OPTIONS_CHEATS_LIST = 28,
    SCENE_NAVIGATION = 29,
    SCENE_WII_CURSOR = 30,
    SCENE_ROAD_TO_STRIKERS_CUP = 31,
    SCENE_CUP_SCHEDULE = 32,
    SCENE_GAME_RESULTS = 33,
    SCENE_CUP_KNOCKOUT = 34,
    SCENE_CUP_FINAL_ROUNDS = 35,
    SCENE_CUP_STANDINGS = 36,
    SCENE_CUP_GOLDEN_BOOT = 37,
    SCENE_CUP_BRICK_WALL = 38,
    SCENE_CUP_NEWS = 39,
    SCENE_ONLINE_MENU = 40,
    SCENE_ONLINE_RANKED = 41,
    SCENE_ONLINE_UNRANKED = 42,
    SCENE_ONLINE_GUEST_CONTROLLER_SELECT = 43,
    SCENE_ONLINE_INVITE_PLAYERS = 44,
    SCENE_ONLINE_INVITE_PREVIEW = 45,
    SCENE_ONLINE_RANKING = 46,
    SCENE_ONLINE_FRIENDS = 47,
    SCENE_ONLINE_FRIEND_CODE_ENTRY = 48,
    SCENE_ONLINE_MATCHMAKING_DRAFT = 49,
    SCENE_ONLINE_FRIENDS_DRAFT = 50,
    SCENE_ONLINE_LOGIN = 51,
    SCENE_ONLINE_INVITE_RESPONSE = 52,
    SCENE_ONLINE_INVITE_STATUS = 53,
    SCENE_ONLINE_MII_SELECT = 54,
    SCENE_ONLINE_MII_SELECT_OVERLAY = 55,
    SCENE_ONLINE_FRIENDS_CHOOSE_SIDES = 56,
    SCENE_ONLINE_CONNECTION_QUALITY = 57,
    SCENE_HOF_PROFILE = 58,
    SCENE_HOF_TROPHY_SUMMARY = 59,
    SCENE_HOF_UNLOCK_SUMMARY = 60,
    SCENE_HOF_CHALLENGE_SUMMARY = 61,
    SCENE_HOF_FIRE_CUP = 62,
    SCENE_HOF_STRIKER_CUP = 63,
    SCENE_HOF_CRYSTAL_CUP = 64,
    SCENE_HOF_PLAYER_CARDS = 65,
    SCENE_HOF_FIRE_CUP_HISTORY = 66,
    SCENE_HOF_FIRE_GOLDEN_BOOT_HISTORY = 67,
    SCENE_HOF_FIRE_BRICK_WALL_HISTORY = 68,
    SCENE_HOF_STRIKER_CUP_HISTORY = 69,
    SCENE_HOF_STRIKER_GOLDEN_BOOT_HISTORY = 70,
    SCENE_HOF_STRIKER_BRICK_WALL_HISTORY = 71,
    SCENE_HOF_CRYSTAL_CUP_HISTORY = 72,
    SCENE_HOF_CRYSTAL_GOLDEN_BOOT_HISTORY = 73,
    SCENE_HOF_CRYSTAL_BRICK_WALL_HISTORY = 74,
    SCENE_CHALLENGE_SELECT = 75,
    SCENE_STRIKERS_101_SELECT = 76,
    SCENE_CHALLENGE_NEWS = 77,
    SCENE_CHOOSE_SIDES_TOURNAMENT = 78,
    SCENE_HEALTH_WARNING = 79,
    SCENE_PAUSE = 80,
    SCENE_PAUSE_CHOOSE_SIDES = 81,
    SCENE_PAUSE_AUDIO_OPTIONS = 82,
    SCENE_PAUSE_VISUAL_OPTIONS = 83,
    SCENE_STRIKERS_101_PAUSE = 84,
    SCENE_LESSON = 85,
    SCENE_STRIKERS_101_LESSONS = 86,
    SCENE_LESSON_MOVIE = 87,
    OVERLAY_HUD = 89,
    OVERLAY_IN_GAME_TEXT = 90,
    OVERLAY_POST_GAME_RESULTS = 91,
    OVERLAY_POST_GAME_STATISTICS = 92,
    OVERLAY_ONLINE_RANKING = 93,
    OVERLAY_STRIKER_TIMES = 94,
    OVERLAY_GOAL = 95,
    OVERLAY_DEMO = 96,
    OVERLAY_TICKER = 97,
    OVERLAY_X2_STS = 98,
    OVERLAY_LOADING = 99,
    OVERLAY_MEGA_STRIKE_METER = 100,
    OVERLAY_PIP = 101,
    OVERLAY_SUPER_ABILITY = 102,
    OVERLAY_CHALLENGE_PREVIEW = 103,
    OVERLAY_CONTROLLER_MAP = 104,
    OVERLAY_DEFENSIVE_PLAY = 105,
};

enum ScreenMovement
{
    SCREEN_NOTHING = 0,
    SCREEN_FORWARD = 1,
    SCREEN_BACK = 2,
};

struct SceneEntry
{
    SceneList mSceneID;
    const char* mFenFileName;
}; // size 0x8

extern SceneEntry SceneEntryTable[];

class BaseGameSceneManager
{
public:
    BaseGameSceneManager();
    virtual ~BaseGameSceneManager();
    virtual BaseSceneHandler* Push(SceneList newscene, ScreenMovement movement, bool popfirst);
    BaseSceneHandler* GetScene(SceneList scene);
    BaseSceneHandler* GetCurrentScene() const
    {
        return mCurrentStackDepth != 0 ? mBaseSceneHandlerStack[mCurrentStackDepth - 1] : 0;
    }
    virtual void Pop();
    void PopEntireStack();
    void PopToScene(SceneList scene);
    SceneList GetSceneType(BaseSceneHandler* scene);
    bool IsOnStack(SceneList scene);
    const char* GetFileName(SceneList scene);
    void PushLoadingScene(bool popfirst);

    static const u32 MAX_SCENE_DEPTH = 32;

    /* 0x04 */ unsigned long mCurrentStackDepth;
    /* 0x08 */ SceneList m_sceneStack[MAX_SCENE_DEPTH];
    /* 0x88 */ BaseSceneHandler* mBaseSceneHandlerStack[MAX_SCENE_DEPTH];
}; // size 0x108


BaseGameSceneManager* GetOverlayManager();
extern BaseGameSceneManager* g_pOverlayManager;

class GLResourcePool;

void CreateFEResourcePool();
void CreateLargeFEResourcePool();
void DestroyFEResourcePool();
void LoadFEMiniBundle(const char* bundleFileName);
bool UnloadFEMiniBundle();
GLResourcePool* GetFEResourcePool();

#endif // GAME_BASE_GAME_SCENE_MANAGER_H
