#pragma once

#include <dwc/dwc_ranking.h>
#include <revolution/types.h>

#ifdef __cplusplus
extern "C"
{
#endif

    typedef enum
    {
        DWCi_ENC_SESSION_STATE_CANCELED,
        DWCi_ENC_SESSION_STATE_ERROR,
        DWCi_ENC_SESSION_STATE_INITIAL,
        DWCi_ENC_SESSION_STATE_INITIALIZED,
        DWCi_ENC_SESSION_STATE_REQUEST,
        DWCi_ENC_SESSION_STATE_GETTING_TOKEN,
        DWCi_ENC_SESSION_STATE_GOT_TOKEN,
        DWCi_ENC_SESSION_STATE_SENDING_DATA,
        DWCi_ENC_SESSION_STATE_COMPLETED
    } DWCiRankingSessionState;

    typedef enum
    {
        DWCi_ENC_SESSION_SUCCESS,
        DWCi_ENC_SESSION_ERROR_NOTINITIALIZED,
        DWCi_ENC_SESSION_ERROR_NOMEMORY,
        DWCi_ENC_SESSION_ERROR_INVALID_KEY
    } DWCiRankingSessionResult;

#define DWCi_RANKING_SESSION_STATE_CANCELED DWCi_ENC_SESSION_STATE_CANCELED
#define DWCi_RANKING_SESSION_STATE_ERROR DWCi_ENC_SESSION_STATE_ERROR
#define DWCi_RANKING_SESSION_STATE_INITIAL DWCi_ENC_SESSION_STATE_INITIAL
#define DWCi_RANKING_SESSION_STATE_INITIALIZED DWCi_ENC_SESSION_STATE_INITIALIZED
#define DWCi_RANKING_SESSION_STATE_REQUEST DWCi_ENC_SESSION_STATE_REQUEST
#define DWCi_RANKING_SESSION_STATE_GETTING_TOKEN DWCi_ENC_SESSION_STATE_GETTING_TOKEN
#define DWCi_RANKING_SESSION_STATE_GOT_TOKEN DWCi_ENC_SESSION_STATE_GOT_TOKEN
#define DWCi_RANKING_SESSION_STATE_SENDING_DATA DWCi_ENC_SESSION_STATE_SENDING_DATA
#define DWCi_RANKING_SESSION_STATE_COMPLETED DWCi_ENC_SESSION_STATE_COMPLETED

#define DWCi_RANKING_SESSION_SUCCESS DWCi_ENC_SESSION_SUCCESS
#define DWCi_RANKING_SESSION_ERROR_NOTINITIALIZED DWCi_ENC_SESSION_ERROR_NOTINITIALIZED
#define DWCi_RANKING_SESSION_ERROR_NOMEMORY DWCi_ENC_SESSION_ERROR_NOMEMORY
#define DWCi_RANKING_SESSION_ERROR_INVALID_KEY DWCi_ENC_SESSION_ERROR_INVALID_KEY

    void DWCi_RankingSessionInitialize(BOOL releaseserver, const char* initdata);
    void DWCi_RankingSessionShutdown(void);
    DWCiRankingSessionResult DWCi_RankingSessionPutAsync(u32 category, s32 pid, DWCRnkRegion region, s32 score, void* data, u32 size);
    DWCiRankingSessionResult DWCi_RankingSessionGetAsync(DWCRnkGetMode mode, u32 category, s32 pid, DWCRnkRegion region, DWCRnkGetParam* param);
    DWCiRankingSessionState DWCi_RankingSessionProcess(void);
    void* DWCi_RankingSessionGetResponse(u32* size);

#ifdef __cplusplus
}
#endif
