#ifndef GAME_AI_FIELDER_DESIRE_TYPES_H
#define GAME_AI_FIELDER_DESIRE_TYPES_H

enum eFielderDesireState
{
    FIELDER_DESIRE_NONE = -1,
    FIELDER_DESIRE_CUT_AND_BREAK = 1,
    FIELDER_DESIRE_DEFEND_POS = 2,
    FIELDER_DESIRE_DEKE = 3,
    FIELDER_DESIRE_GET_IN_POSITION = 4,
    FIELDER_DESIRE_GET_OPEN = 5,
    FIELDER_DESIRE_HIT = 6,
    FIELDER_DESIRE_INTERCEPT_BALL = 7,
    FIELDER_DESIRE_MARK = 8,
    FIELDER_DESIRE_RUN_TO_NET = 9,
    FIELDER_DESIRE_RUN_UPFIELD = 10,
    FIELDER_DESIRE_RUN_DOWNFIELD = 11,
    FIELDER_DESIRE_RUN_IN_DIRECTION = 12,
    FIELDER_DESIRE_RUN_TO_TARGET = 13,
    FIELDER_DESIRE_PASS = 14,
    FIELDER_DESIRE_SHOOT = 15,
    FIELDER_DESIRE_SLIDE_ATTACK = 16,
    FIELDER_DESIRE_USE_POWERUP = 17,
    FIELDER_DESIRE_PREPARE_PASS = 18,
    FIELDER_DESIRE_WINDUP_SHOT = 19,
    FIELDER_DESIRE_USER_CONTROLLED = 20,
    FIELDER_DESIRE_FINISH_ACTION = 21,
    FIELDER_DESIRE_RECEIVE_PASS = 22,
    FIELDER_DESIRE_SUPER_POWER = 23,
    FIELDER_DESIRE_STAR = 24,
    FIELDER_DESIRE_MUSHROOM = 25,
    FIELDER_DESIRE_SLIPPERY = 26,
    FIELDER_DESIRE_GOOEY = 27,
    FIELDER_DESIRE_SHRINK = 28,
    FIELDER_DESIRE_FROZEN = 29,
    FIELDER_DESIRE_CONFUSED = 30,
    FIELDER_DESIRE_WAIT = 31,
    FIELDER_DESIRE_MEGA_STRIKE = 32,
    FIELDER_DESIRE_DO_NOTHING = 33,
    FIELDER_DESIRE_STEERING = 34,
    FIELDER_DESIRE_WALUIGI_WALL = 35,
};

#endif // GAME_AI_FIELDER_DESIRE_TYPES_H
